### ISSUE TITLE
send_custom_event demo

### ISSUE THREAD

**Issue by YuanboBQ** [marcus-nystrom/Titta#10]
Hi, Marcus, thanks for your very useful package. I have a question about how to send custom event when using the TalkToProLab. I want to send my custom events (e.g., trials began, response) , but I do not know how to use` ttl.send_custom_event`, and did not find any demos how to use it. I have a try to use `ttl.send_custom_event(rec['recording_id'], str(t_offset))`  , but it did not work. Could you provide some builder demos about how to use  `ttl.send_custom_event` function.

**Comment by marcus-nystrom** [comment]
> Hi, Marcus, thanks for your very useful package. I have a question about how to send custom event when using the TalkToProLab. I want to send my custom events (e.g., trials began, response) , but I do not know how to use` ttl.send_custom_event`, and did not find any demos how to use it. I have a try to use `ttl.send_custom_event(rec['recording_id'], str(t_offset))` , but it did not work. Could you provide some builder demos about how to use `ttl.send_custom_event` function.

Hi, 

I have not yet implemented this, but have a look at Titta's Matlab-page where you can find some examples of how to implement custom events (TalkToProLab.m)
