### ISSUE TITLE
Tobii and Titta Timing

### ISSUE THREAD

**Issue by jgeller112** [marcus-nystrom/Titta#12]
Hello, 

I am using a X2-30 Tobii tracker with Tittia. Below is a data frame that includes system_time_stamp and the device_time_stamp columns provided by Tittia.  How are these timestamps calculated? The tracker should be sampling every 30 ms, and that is clearly not the case.  The time1 variable was calculated by dividing the time stamp by 1+6E. 

```
time1=(system_time_stamp - system_time_stamp[1])/1000000) #start time at fixation start for each trial. 
#subtract first time point from each stamp. 
```
```
 participant trial system_time_stamp device_time_stamp time1
   <lgl>       <chr>           <int64>           <int64> <dbl>
 1 NA          0         2163331982574  1173924160796621 0    
 2 NA          0         2163332365089  1173924161179154 0.383
 3 NA          0         2163332395739  1173924161209815 0.413
 4 NA          0         2163332555300  1173924161369367 0.573
 5 NA          0         2163332719376  1173924161533440 0.737
 6 NA          0         2163332758796  1173924161572861 0.776
 7 NA          0         2163332804326  1173924161618357 0.822
 8 NA          0         2163332860401  1173924161674401 0.878
 9 NA          0         2163332899621  1173924161713607 0.917
10 NA          0         2163333111208  1173924161925161 1.13 


```

**Comment by jgeller112** [comment]
It seems later samples are correctly sampled at ~33 hz. It appears that when samples are missing (validity = 0) the timing become more erratic. I wonder why that is.

**Comment by marcus-nystrom** [comment]
Hi,

I suggest you forward this question to Tobii support. Titta only gets the
timestamps reported from Tobii's SDK. My guess would be that when data are
missing the image sensor goes into a full frame search, making the sample
rate less stable and consistent.

Best,
Marcus

**Comment by jgeller112** [comment]
Thanks, @marcus-nystrom! I figured that was the case.
