### ISSUE TITLE
General question about recording eye tracking data while using a software

### ISSUE THREAD

**Issue by UBela** [marcus-nystrom/Titta#13]
Hi,
I recently started working with Titta and want to record ET data while using a specific software. 
From the demos I was under the impression that Titta needs a PsychoPy visual.Window in order to record data. My first guess was to create a transparent window in PsychoPy and use that as an overlay but I could not find a way to change the alpha value of a window. 
If it is possible to record data without the need for a visual.Window how can I safely close the calibration Window and start the recording process of the screen?

**Comment by marcus-nystrom** [comment]
Hi,

Happy to hear that you found your way to Titta!
Titta does not need a PsychoPy window to record data. After calibration,
you can close the PsychoPy window (win.close) and then start the recording
(look at the read_me.py demo)

Thanks,
Marcus

**Comment by UBela** [comment]
Thanks! :)
