### ISSUE TITLE
merge msg_data and gaze_data into one file

### ISSUE THREAD

**Issue by amandasaksida** [marcus-nystrom/Titta#16]
Hi, 
i'm a newbie both to psychopy and titta, and have a possibly trivial question. 
Following the examples in the demos, i have created two separate dataframes for gaze_data and tracker messages at the end of the experiment, written into two separate tsv files. 
How do i join them in one file (with one single system_time_stamp column)? 
Thank you in advance! 
Amanda

**Comment by marcus-nystrom** [comment]
Hi Amanda,

Please have a look at
https://github.com/marcus-nystrom/Titta/blob/master/resources/extract_trial_data_and_detect_fixations.py

The function 'Textract_trial_data' shows how to extract eye tracking data
associated with a certain message.

Marcus

**Comment by amandasaksida** [comment]
Hi Marcus, 
thanks for the info; all clear now. 
Amanda
