### ISSUE TITLE
keypress causing calibration error

### ISSUE THREAD

**Issue by amandasaksida** [marcus-nystrom/Titta#17]
Hi, 
We have noticed a small issue while implementing the titta's calibration into the Psychopy Builder experiment. The calibration function (myTobii.calibrate) skips the face adjustment screen if there is an event before the calibration that requires waiting for a keypress “space” (for example: keyboard.Keyboard().waitKeys(keyList=['space'])  )
Same happens if space is pressed by mistake before the calibration function onset. 
If other keypresses are being waited for, and pressed, the calibration works well. Fyi, the keyboard is using the ptb backend. 
(System specifications: Python 3.6 running on MacBook Air (13-inch, 2017), OS.X. 10.14.6. Eye-tracker: Tobii Pro Nano)

I also have a question regarding the modifications of the calibration procedure. To better attract attention (the exp is for infants), I'd like to adapt Titta's calibration to play custom made movies and also make a sound when displayed. But before starting to dig into this, i was wondering if such thing may already have been done by someone else (i've seen something similar was done for matlab (https://github.com/dcnieho/Titta/issues/14). 

Thanks in advance. 
Best, 
Amanda

**Comment by amandasaksida** [comment]
Hi, 
I have another question regarding gaze data. The columns from the gdata (Tobii.py) are being stored in my csv file, and to locate the gaze on the screen, i'm assuming i need to take the gaze_point_on_display_area data from both eyes and average them. However, in these columns i get proportion values (from 0 to 1) instead of pixel values (what i got with the old Tobii T120). I have been looking into the documentation but i fail to see how to transform them into the pixel data. Thanks in advance! 
Amanda

**Comment by marcus-nystrom** [comment]
Hi Amanda,

Thanks for your feedback! I just committed a change that I think will solve
the problem. Added a line that will flush the events in the mouse buffer,
so hopefully the key press will no longer lead to a skipped setup screen.

Best,
Marcus

**Comment by marcus-nystrom** [comment]
Hi Amanda,

The Tobii coordinate system is indeed 0->1, where (0, 0) refers to the
upper left corner of the screen and (1, 1) to the bottom right corner of
the screen. Simply multiply the coordinate values with the horizontal and
vertical resolution of your screen to transform into pixels.

Best,
Marcus
