### ISSUE TITLE
Setting up the viewing distance

### ISSUE THREAD

**Issue by UBela** [marcus-nystrom/Titta#18]
Hey,
I haven't worked with psychopy before and wanted to change the viewing distance. However changing it to, e.g. mon.setDistance(70) did not change the distance during the calibration process. Am i missing something here?
Thanks in advance,
Béla

**Comment by marcus-nystrom** [comment]
Hi Béla,

Unfortunately the toolbox doesn't work that way right now. The head
animation during setup is designed to put the head in the center of the
head box, where the best data quality can be recorded.
You can of course record at other distances as well, but data quality will
generally be worse. May I ask why you choose to record at a non-optimal
distance?

If you necessarily want to record at a distance of 70 cm, and want the
circles to overlap at this distance during calibration setup, you can tweak
the parameters in the EThead class (in helpers_tobii.py).

Best,
Marcus
