### ISSUE TITLE
Cannot set frequency

### ISSUE THREAD

**Issue by victoriawardell** [marcus-nystrom/Titta#19]
Hello! 

I'm trying to set up Titta and am running into a similar issue as was addressed in this Titta for Matlab post (https://github.com/dcnieho/Titta/issues/34). 

We are using Python version 3.6.6 and PsychoPy version 2021.2.3. We have a Tobii Pro Spectrum and are just trying to run your demo experiments. We encounter an error with the default frequency (see code below) but attempting to overwrite the default with the code `settings.freq = 150` doesn't fix the error.

Any advice you can give would be greatly appreciated! 

> C:\Program Files\PsychoPy\Lib\site-packages\Titta-master\demos>python -m read_me.py
> pygame 1.9.6
> Hello from the pygame community. https://www.pygame.org/contribute.html
> [150.0, 120.0, 60.0] 600
> Traceback (most recent call last):
>   File "C:\Program Files\PsychoPy\lib\runpy.py", line 183, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "C:\Program Files\PsychoPy\lib\runpy.py", line 109, in _get_module_details
>     __import__(pkg_name)
>   File "C:\Program Files\PsychoPy\Lib\site-packages\Titta-master\demos\read_me.py", line 39, in <module>
>     tracker.init()
>   File "C:\Program Files\PsychoPy\lib\site-packages\titta\Tobii.py", line 185, in init
>     self.set_sample_rate(self.settings.SAMPLING_RATE)
>   File "C:\Program Files\PsychoPy\lib\site-packages\titta\Tobii.py", line 2056, in set_sample_rate
>     assert np.any([int(i) == Fs for i in self.tracker.get_all_gaze_output_frequencies()]), "Supported frequencies are: {}".format(self.tracker.get_all_gaze_output_frequencies())
> AssertionError: Supported frequencies are: (150.0, 120.0, 60.0)
>

**Comment by marcus-nystrom** [comment]
Hi!

Glad to see that you found your way to Titta! In the python toolbox, you
change the sampling frequency as follows:
settings.SAMPLING_RATE = 150

Hope this works!

Best,
Marcus

**Comment by victoriawardell** [comment]
That worked- tank you so much!
