### ISSUE TITLE
"AttributeError: module 'tobii_research' has no attribute 'CAPABILITY_HAS_EYE_OPENNESS_DATA'"

### ISSUE THREAD

**Issue by RebeccaHirst** [marcus-nystrom/Titta#26]
After following the installation instructions, the following error always occurs when running the readme.py in [PsychoPy 2022.2.5 ](https://github.com/psychopy/psychopy/releases/tag/2022.2.5)

"AttributeError: module 'tobii_research' has no attribute 'CAPABILITY_HAS_EYE_OPENNESS_DATA'"

**Comment by marcus-nystrom** [comment]
Probably because PsychoPy does not include the most recent version of
tobii_research. Try updating tobii_research to the latest version (1.10.1):
pip install tobii_research --upgrade

**Comment by marcus-nystrom** [comment]
Accepted pull request that allows older versions of tobii_research to be used.
