### ISSUE TITLE
External Presenter Error: Exclusive connection to service already established. Only one allowed at a time. Please disconnect

### ISSUE THREAD

**Issue by ShubhamKaushal15** [marcus-nystrom/Titta#32]
Hi, I'm unfamiliar with websocket protocols so I'm not sure whom to ask about this problem I'm facing. `ttl.get_state()` in [read_me_TalkToProLab.py](https://github.com/marcus-nystrom/Titta/blob/3474a34cab6ea9a44011d53fa0e35debe8a29175/demo_experiment/read_me_TalkToProLab.py#L110) gives me an error which I'm able to reproduce using the code below. Does anyone have any idea why this might be happening?
```
>>> from websocket import create_connection
>>> import json
>>> address = create_connection('ws://localhost:8080/record/externalpresenter?client_id=RemoteClient')
>>> req = {"operation": "GetState"}
>>> msg_dict = json.dumps(req)      
>>> address.send(msg_dict)
31
>>> address.recv()
'{"reason":"Exclusive connection to service already established. Only one allowed at a time. Please disconnect.","status_code":104,"operation":"GetState"}'
```

Also, if someone could give me an intuition as to how these websocket links are obtained, that would be very helpful. I found that a connection to the link above is not made when Tobii Pro Lab is not running, but I was unable to find websocket links mentioned anywhere in their documentation. Thank you so much for your help in advance!

**Comment by marcus-nystrom** [comment]
Hi @ShubhamKaushal15,

Looks like you're already connected in Pro Lab before running the psychopy script. The 'External Presenter' button should be red and say 'not connected' before starting the psychopy script, otherwise it tries to connect twice (hence the error).
