### ISSUE TITLE
Index 1 is out of bounds for axis 1 with size 1 during calibration

### ISSUE THREAD

**Issue by Martenren** [marcus-nystrom/Titta#33]
Hello, I am trying to use Titta with PsychoPy.

It seems to connect succesfully to Tobii Pro Lab, but while executing the test read_me_TalkToProLab I get an error during the calibration phase. I have provided a youtube link to show when the error occurs. I am using a Tobii Pro Nano calibrated with Tobii Pro Eye Tracker Manager.

It seems to provide to different errors. one when the application closes : 

"Index 1 is out of bounds for axis 1 with size 1"

And the other one when I stop the python execution : 

"AssertionError: {'reason': 'Exclusive connection to service already established. Only one allowed at a time. Please disconnect. ', 'status_code': 104, 'operation': 'StopRecording'}

link to the video : 
https://youtu.be/4yjdKfx2ND0

I have tried debugging myself but to no success, so I hope someone can answer me to what I am doing wrong.

Thank you for your time.

**Comment by marcus-nystrom** [comment]
Hi @Martenren 

Looks like you're already connected in Pro Lab before running the psychopy script. The 'External Presenter' button should be red and say 'not connected' before starting the psychopy script, otherwise it tries to connect twice (hence the error).
