### ISSUE TITLE
Titta in OpenSesame has smaller and more centered calibration dots 

### ISSUE THREAD

**Issue by dev-jam** [marcus-nystrom/Titta#34]
I took the code from the demo experiment (init, start_recording, send_message, save_data, helpers.MyDot2(win)) and implemented it as separate inline scripts in an OpenSesame experiment with psychopy as backend. I omitted the creation of a window because OpenSesame creates its own window. Everything worked nicely but when I compared the calibration output from the OpenSesame experiment with the demo experiment I found the calibration dots are smaller and are more located to the center than the vanilla experiment. OpenSesame was set to 1920x1080 and the pictures also had the same resolution. I suspect OpenSesame creates windows a bit different than the code in the demo.

**Comment by dcnieho** [comment]
Images to go with the report:
![355438410_1016055866430202_4676800473578586723_n](https://github.com/marcus-nystrom/Titta/assets/1787673/9937c9f9-4845-4b60-944e-175695b9922f)
![355488358_1769980066810015_5869317843635701142_n](https://github.com/marcus-nystrom/Titta/assets/1787673/2328065e-fecf-47d0-8c17-3a4370883931)
![355696281_795428768656267_583529478290119816_n](https://github.com/marcus-nystrom/Titta/assets/1787673/c72c0d38-9dcb-41fe-974e-e26d63f186aa)
![355636082_1751647715291316_3141074540878689519_n](https://github.com/marcus-nystrom/Titta/assets/1787673/f6af9600-886d-4cc6-897b-04c848051200)

**Comment by dcnieho** [comment]
Marcus, does your code expect one of the specific coordinate systems that Psychopy implements? Perhaps OpenSesame uses another and that causes these issues? Just the first thing i think of

**Comment by dev-jam** [comment]
OpenSesame creates psychopy windows with pxs as unit, compared to deg in Titta:

https://github.com/open-cogsci/OpenSesame/blob/milgram/openexp/_canvas/psycho.py

line 152:

`units=u'pix',`

**Comment by dev-jam** [comment]
Found out that a psychopy window can easily switch between pxs, norm and degree but when working with degree, psychopy in OpenSesame needs the monitor distance and dimensions. You can change these settings in ~/.psychopy3/monitors/testMonitor.json or create a new monitor there and select it in OpenSesame. Now the dots have the right size and coordinates.

**Comment by marcus-nystrom** [comment]
Thanks for reporting and testing with OpenSesame! I have now changed such that Titta can run without first setting up a monitor.
