### ISSUE TITLE
Illegal character in LICENSE.md

### ISSUE THREAD

**Issue by dev-jam** [marcus-nystrom/Titta#35]
When building a deb from the wheel with wheel2deb on debian I get an error: 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 621: invalid start byte

The problem is the presence of illegal characters in LICENSE.md

With RC7 I only had to replace a couple of "SPA" characters with the MINUS sign and then it worked, but with RC8 I also found "STS" and "CCH" characters. Replacing them did not solve the issue this time. So I suspect there are more hidden illegal characters. 

I then created a new source package with: 

`python3 setup.py sdist` 

With this source package I could then succesfully build a deb with stdeb.

**Comment by marcus-nystrom** [comment]
Replaced some minus signed and quotation marks. Should hopefully do the trick.

**Comment by dev-jam** [comment]
Almost there, there is still one character in line 47:

       A. __Offer from the Licensor � Licensed Material.__ Every recipient of the Licensed Material automatically receives an offer from the Licensor to exercise the Licensed Rights under the terms and conditions of this Public License.

I checked it with the following command (terminal needs to be set to utf-8):

`grep -axv '.*' LICENSE.md`

**Comment by marcus-nystrom** [comment]
got it! Thanks. updated.

**Comment by dev-jam** [comment]
rc10 is working perfectly now. Thanks!
