### ISSUE TITLE
control over storage location of calibration files

### ISSUE THREAD

**Issue by dev-jam** [marcus-nystrom/Titta#37]
For the Titta OpenSesame plugin I need control over the storage location of the .p file and the calibration_image/validation_image. In linux these files are stored directly in the user home directory (~/home) but on Windows titta tries to store it in a location where it does not have write permissions so the plugin is not working in Windows. 

My preference is to store these files in the same directory as where I now store the .h5 data files, which is in the folder where the OpenSesame experiment is located. And insert the subjectnr from OpenSesame in these filenames.

**Comment by marcus-nystrom** [comment]
Where calibration/validation images (.png) and data (p.) are stored now controlled by setting a path (directly in Titta.py or through settings = Titta.get_defaults(et_name))

**Comment by dev-jam** [comment]
I got it working, files are saved to the correct location and the plugin is working now in Windows.

One aesthetical problem: for the .h5 and .json files I now get double file names: FILENAME_FILENAME.h5 (and .json). 

If I change line 1809 to:

```
        #fname = os.sep.join([fname + filename_ext])
        fname = self._add_to_name(filename_ext)
```

I don't get the double file names but the file names end with a underscore: FILENAME_.h5
I tried to change the code a bit with regard to '_add_to_name' but it is hard to serve both the data files as the calibration files. Maybe you can look into this and change the code a bit broader?

**Comment by marcus-nystrom** [comment]
should be fixed now
