### ISSUE TITLE
underscores in message variable 'stimulusname' 

### ISSUE THREAD

**Issue by dev-jam** [marcus-nystrom/Titta#38]
In extract_trial_data.py, part # Read message for onset and offset:

In the onset_stimulusname and offset_stimulusname, stimulusname can have no underscores . Everything after the second underscore is omitted. I use filenames with underscores as 'stimulusname', so I have to replace my underscores in my filenames.

**Comment by marcus-nystrom** [comment]
Thanks! Fixed.

**Comment by dev-jam** [comment]
Works perfectly now. Thanks!
