### ISSUE TITLE
compute_data_quality and detect_fixations cannot handle an empty trial tsv file 

### ISSUE THREAD

**Issue by dev-jam** [marcus-nystrom/Titta#39]
compute_data_quality.py and detect_fixations.py crash when they encounter an empty trial tsv file (file with header but no data) generated by extract_trial_data.py.

Manually removing the empty files solves this at the moment.

**Comment by marcus-nystrom** [comment]
Thanks for reporting. Fixed.

**Comment by dev-jam** [comment]
change of the location of the h5 and json files was not integrated yet in compute_data_quality.py. Created a pull request for that. After that it works perfectly. Thanks!
