### ISSUE TITLE
removal of dependency on demo_experiment in plot_scanpath

### ISSUE THREAD

**Issue by dev-jam** [marcus-nystrom/Titta#40]
It would be nice to have no dependency on demo_experiment in plot_scanpath. 
And make plot_scanpath the 5th step in the readme by putting plot_scanpath.py in the 'demo_analyses' folder, which gets the 'allfixations.txt' from the 'output' folder and the images from a 'stim' or 'pictures' folder (where you have to manually add the pictures).
And last, maybe a separate 'data' folder for the .h5 and .json files.

**Comment by marcus-nystrom** [comment]
Appreciate the testing and suggestions! I have followed your suggestions.

**Comment by dev-jam** [comment]
Works perfectly. Another suggestion:

- already put the empty 'stimuli' folder in here
- save the output images to the folder: results/subject/scanplot_stimulusname. Data quality files could also be in results.
