### ISSUE TITLE
comma missin in toby.py

### ISSUE THREAD

**Issue by amandasaksida** [marcus-nystrom/Titta#44]
Hi, 
just wanted to let you know there is a comma missing in the self.header list in the Tobii.py file, line 145. 

I also have a few questions regarding Tobii_dummy.py: 
1. the output columns defined in sample_list and self.header (Tobii.py) are not corresponding. Also, the lists have different names. Is there a particular reason for this?
2. sample_list is defined at the beginning  of the script while in Tobii.py, the self.header is defined within the class myTobii. Because of this, output text file columns in an experimental script must be defined manually, hence any change in titta package may cause error in compiling output text file. Can this be amended as well? 

Thanks in advance, 
Amanda

**Comment by marcus-nystrom** [comment]
Hi and thanks for you input!

1. self.header was a rest from a previous version of Titta and is no longer needed. I have removed it. The names in sample_list in Tobii_dummy.py are the correct ones.
2. " output text file columns in an experimental script must be defined manually". What do you mean by this? When running in dummy mode, no input is saved, and save_data does nothing.

**Comment by amandasaksida** [comment]
Hi,
Thanks for your swift reply!

On 19 Sep 2023, at 12:37, Marcus Nyström ***@***.******@***.***>> wrote:



Hi and thanks for you input!

  1.  self.header was a rest from a previous version of Titta and is no longer needed. I have removed it. The names in sample_list in Tobii_dummy.py are the correct ones.
  2.  " output text file columns in an experimental script must be defined manually". What do you mean by this? When running in dummy mode, no input is saved, and save_data does nothing.

In fact i was referring to the definition of self.header and saving data when running the script with the tracker initiated.
In the current version of the psychopy script that i’m using, the data from the gaze_data_container are stored in a list (or an array?). To compile the final csv output file, the names of the columns had to be added manually since they were not defined at the beginning of the Tobii.py script.

I’ll check with my programmer if they can be retrieved from the Tobii_dummy script instead, once i’m back in the lab.
But in any case it’s a minor issue and it works as is now.

Thanks again!
Amanda



Amanda Saksida, PhD, researcher
……………………………………………..
Struttura Complessa di Otorinolaringoiatria e Audiologia
IRCCS Burlo-Garofolo, Via dell'Istria 65/1, 34137 Trieste, Italy
email: ***@***.******@***.***>
tel: +39.040.3785.537




[IRCCS Burlo Garofolo - 5x1000 - Finanziamento della ricerca sanitaria - codice fiscale 00124430323]

**Comment by marcus-nystrom** [comment]
Sounds like you're using an old version of Titta. Please update to the most recent version.

**Comment by amandasaksida** [comment]
Thanks. 
I have another question: we tried to install the updated version of titta on a previously unused mac (Mac OS X 10.13.6) with python 3.10 (pip 23.2.1) and psychopy-2023.2.2 installed. Installation results in error due conflicting dependencies (on TittaPy). When only one of the versions is installed, the error message is that no matching distribution is found for that version. We don't seem to find the solution for this insofar.

**Comment by marcus-nystrom** [comment]
Could be that Python 3.10 causes some problems. PsychoPy strongly recommends using Python 3.8.

**Comment by dcnieho** [comment]
The minimum supported OSX version for TittaPy is 10.14, that's likely the cause of your issue
