### ISSUE TITLE
data output columns in titta

### ISSUE THREAD

**Issue by amandasaksida** [marcus-nystrom/Titta#45]
Hi, i have request regarding the data columns from Tobii Pro Nano. 
It is unclear what is the current list of the output columns from Tobii. They are only defined in the Tobii_dummy.py files of titta, and they differ in the previous and the current versions. I list both versions below. 
Given that we want to give an instant feedback about the pupil position and validity during the experiment, we have to define the columns from which the data is taken. So far i have tried to define the column using the list from the current (and the old) version, but it doesn't seem to be giving me the right data. Is it possible to obtain the correct version of the data output column, and where do we search for them? 
Thanks in advance, 
Amanda 

Current version: 
[
'device_time_stamp', 'system_time_stamp',
       'left_gaze_point_on_display_area_x',
       'left_gaze_point_on_display_area_y',
       'left_gaze_point_in_user_coordinates_x',
       'left_gaze_point_in_user_coordinates_y',
       'left_gaze_point_in_user_coordinates_z', 'left_gaze_point_valid',
       'left_gaze_point_available', 'left_pupil_diameter', 'left_pupil_valid',
       'left_pupil_available', 'left_gaze_origin_in_user_coordinates_x',
       'left_gaze_origin_in_user_coordinates_y',
       'left_gaze_origin_in_user_coordinates_z',
       'left_gaze_origin_in_track_box_coordinates_x',
       'left_gaze_origin_in_track_box_coordinates_y',
       'left_gaze_origin_in_track_box_coordinates_z', 'left_gaze_origin_valid',
       'left_gaze_origin_available', 'left_eye_openness_diameter',
       'left_eye_openness_valid', 'left_eye_openness_available',
       'right_gaze_point_on_display_area_x',
       'right_gaze_point_on_display_area_y',
       'right_gaze_point_in_user_coordinates_x',
       'right_gaze_point_in_user_coordinates_y',
       'right_gaze_point_in_user_coordinates_z', 'right_gaze_point_valid',
       'right_gaze_point_available', 'right_pupil_diameter',
       'right_pupil_valid', 'right_pupil_available',
       'right_gaze_origin_in_user_coordinates_x',
       'right_gaze_origin_in_user_coordinates_y',
       'right_gaze_origin_in_user_coordinates_z',
       'right_gaze_origin_in_track_box_coordinates_x',
       'right_gaze_origin_in_track_box_coordinates_y',
       'right_gaze_origin_in_track_box_coordinates_z',
       'right_gaze_origin_valid', 'right_gaze_origin_available',
       'right_eye_openness_diameter', 'right_eye_openness_valid',
       'right_eye_openness_available'
]

Previous version: 
[
    'device_time_stamp',
    'system_time_stamp',
    'left_gaze_point_on_display_area_x',
    'left_gaze_point_on_display_area_y',
    'left_gaze_point_in_user_coordinate_system_x',
    'left_gaze_point_in_user_coordinate_system_y',
    'left_gaze_point_in_user_coordinate_system_z',
    'left_gaze_origin_in_trackbox_coordinate_system_x',
    'left_gaze_origin_in_trackbox_coordinate_system_y',
    'left_gaze_origin_in_trackbox_coordinate_system_z',
    'left_gaze_origin_in_user_coordinate_system_x',
    'left_gaze_origin_in_user_coordinate_system_y',
    'left_gaze_origin_in_user_coordinate_system_z',
    'left_pupil_diameter',
    'left_pupil_validity',
    'left_gaze_origin_validity',
    'left_gaze_point_validity',
    'right_gaze_point_on_display_area_x',
    'right_gaze_point_on_display_area_y',
    'right_gaze_point_in_user_coordinate_system_x',
    'right_gaze_point_in_user_coordinate_system_y',
    'right_gaze_point_in_user_coordinate_system_z',
    'right_gaze_origin_in_trackbox_coordinate_system_x',
    'right_gaze_origin_in_trackbox_coordinate_system_y',
    'right_gaze_origin_in_trackbox_coordinate_system_z',
    'right_gaze_origin_in_user_coordinate_system_x',
    'right_gaze_origin_in_user_coordinate_system_y',
    'right_gaze_origin_in_user_coordinate_system_z',
    'right_pupil_diameter',
    'right_pupil_validity',
    'right_gaze_origin_validity',
    'right_gaze_point_validity'
]

**Comment by marcus-nystrom** [comment]
The keys in the current version are correct. Use them.
Look at the read_my.py demo to see how you access the data in real time,
for instance:

# Get the latest sample
sample = tracker.buffer.peek_N('gaze', 1)

# Extract stuff from this sample
print(sample['left_gaze_point_on_display_area_x'])
print(sample['right_pupil_diameter'])
