### ISSUE TITLE
Question: Pygame/Psychopy

### ISSUE THREAD

**Issue by cataldoe** [marcus-nystrom/Titta#56]
Hello, 

Sorry, I don't fully understand if PsychoPy and Pygame are/are not linked?
Is there any mean to use Titta on an experiment that was built on Pygame?

Thank you for your response

Best
ec

**Comment by marcus-nystrom** [comment]
Yes, you can use Titta with PyGame (and without PsychoPy). If you're not
using it with PsychoPy, however, you'd have to implement your own
calibration procedure.
