### ISSUE TITLE
support for Tobii Pro Fusion

### ISSUE THREAD

**Issue by oricon** [marcus-nystrom/Titta#6]
I have a Tobii Pro Fusion 120Hz and am trying to use Titta with psychopy. I modified Titta.py accordingly, 
`elif et_name == 'Tobii Pro Fusion':
        settings.SAMPLING_RATE = 120`

but I still get the "eye tracker type not supported" error. How can I use a Fusion with this code?

**Comment by marcus-nystrom** [comment]
Your edits should do the trick. Have added and committed support for the Fusion. Unfortunately, I don't have one myself, so I can't test it. 

Try the read_me.py demo and make sure to change 
et_name = 'Tobii Pro Fusion'  

Also make sure that you can connect to your eye tracker in Tobii's Eye tracker manager before trying it with Titta.

**Comment by marcus-nystrom** [comment]
> I have a Tobii Pro Fusion 120Hz and am trying to use Titta with psychopy. I modified Titta.py accordingly,
> `elif et_name == 'Tobii Pro Fusion': settings.SAMPLING_RATE = 120`
> 
> but I still get the "eye tracker type not supported" error. How can I use a Fusion with this code?

**Comment by marcus-nystrom** [comment]
Your edits should do the trick. Have added and committed support for the Fusion. Unfortunately, I don't have one myself, so I can't test it.

Try the read_me.py demo and make sure to change
et_name = 'Tobii Pro Fusion'

Also make sure that you can connect to your eye tracker in Tobii's Eye tracker manager before trying it with Titta.

**Comment by oricon** [comment]
Yes its working now, thanks!
