### ISSUE TITLE
Blinks

### ISSUE THREAD

**Issue by jgeller112** [marcus-nystrom/Titta#61]
Hi,

Given the new blink algo, can we expect this to be added to the data stream soon?

**Comment by dcnieho** [comment]
Titta doesn't provide any classified events (fixations, saccades, etc) in its data streams during recording. So blinks are not on the planning either. Is that what you mean?

**Comment by jgeller112** [comment]
Ah. If I remember correctly, I was just using the valid columns as a proxy for blinks. I guess my follow-up Q is can the output you get from Titta be easily passed through the blink algo? That is, are the proper columns saved into the dataset (e.g., eye openness)? I have not used Titta in a while so I dont remember what is saved vs. not.

**Comment by marcus-nystrom** [comment]
Examples of how to use Titta output to detect blinks are given here:
https://github.com/marcus-nystrom/BlinkDetector
