### ISSUE TITLE
cant find read_me.py

### ISSUE THREAD

**Issue by omrishlomy** [marcus-nystrom/Titta#64]
after titta installed in the directory of psychopy, i cant find where read_me.py is.
i do see the titta folder and atoher related folders but not the requested one.
woud like some help, thank you.

**Comment by marcus-nystrom** [comment]
read_me.py is, just like you mention, not located in the titta folder in
the psychopy directory after pip installing it.
You need to download the example demos (including read_me.py) directly from
the GitHub repository.
