### ISSUE TITLE
Binocular Mean Warning

### ISSUE THREAD

**Issue by jgeller112** [marcus-nystrom/Titta#7]
Hello, 

I am using your Titta package to run a X2-30 Compact. After the experiment is over, I am getting the below message with the Slideshow demo that comes with the package:

```
C:\Program Files\PsychoPy3\lib\site-packages\titta\helpers_tobii.py:388: RuntimeWarning: Mean of empty slice
  avg_pos = np.nanmean([xyz_pos_eye_l, xyz_pos_eye_r], axis=0)
C:\Program Files\PsychoPy3\lib\site-packages\titta\Tobii.py:657: RuntimeWarning: Mean of empty slice
  str(int(np.nanmean([l_pos, r_pos])/10.0)), 'cm'])

```

Is there a way to just output each eye and not  average?

**Comment by jgeller112** [comment]
Also, the file is being saved as PKL and not a .tsv file at the end.

**Comment by jgeller112** [comment]
In addition, 

I am trying to convert the .pkl file produced to a readable format at the end of the task, but I am not having any luck. I get an error about filename not being an argument in save_data(), which it clearly is. 

```
tracker.stop_recording(gaze_data=True)
tracker.save_data(filename='testfile')
f = open("testfile.pkl", 'rb')
gaze_data_container = pickle.load(f)
msg_container = pickle.load(f)
external_signal_container = pickle.load(f)
sync_data_container = pickle.load(f)
stream_errors_container = pickle.load(f)
image_data_container = pickle.load(f)
calibration_history = pickle.load(f)
system_info = pickle.load(f)
settings = pickle.load(f)
python_version = pickle.load(f)
f.close()
```

**Comment by marcus-nystrom** [comment]
Hi,

This is warning you can ignore. The warning is related to the visualization
of data during the setup screen.

Best,
Marcus

**Comment by marcus-nystrom** [comment]
Hi,

What is the exact error message?
Did you run the read_my.py example? Did that work?

Thanks,
Marcus

**Comment by jgeller112** [comment]
Everything works. I was just curious about the warning message.
