### ISSUE TITLE
PsychoPy Builder demo for "Talk to ProLab"

### ISSUE THREAD

**Issue by hannahkunde** [marcus-nystrom/Titta#8]
Hi,

I am more than happy that I found your toolbox. Thanks for all the work you put into it!!!

So far, I tried the "general" and the "Talk to ProLab"-demos. Both work. 
Now I wanted to build a PsychoPy-experiment in the builder view and wanted to add the relevant code in code snippets to let PsychoPy communicate with Tobii Pro Lab like in the "TalkToProLab.py"-script. This seems to be more difficult than I thought - do you have any demo where you programmed something like this? If yes, it would be amazing if you could share it with me.

Best,
Hannah

P.S. I also tried the "slideshow_example.psyexp" - here the callibration does not work. Whatever I do, it tells me that the callibration was unsuccessful.

**Comment by marcus-nystrom** [comment]
Dear Hanna,

Unfortunately, I do not have a Builder demo that runs together with the
Tobii Pro Lab software. The reason, as you mention, is that it would
probably be quite messy. It can be done, but I strongly suggest you
implement it in code,  and build on the already available demo script
(TalkToProLab.py).

Best wishes,
Marcus

**Comment by hannahkunde** [comment]
Dear Marcus,
Thank you for your response! Yes, I think for me that is a great solution! 
I was just looking for something easier to use for several of my students who are not at all into programming and need to have more control over the randomization than in Tobii Pro Lab. For them I will probably need to think about something different. Do you have any other suggestions for that?

Best wishes from Germany,
Hannah

**Comment by marcus-nystrom** [comment]
Hi Hanna,

Why not use PsychoPy builder and Titta to collect data?  And then provide
your students with a few additional Python scripts for analysis and
visualization of data?

Best,
Marcus

**Comment by YuanboBQ** [comment]
Hi, Marcus, do you have additional Python (or R) scripts for analysis and visualization of .tsv eye-tracking data. I have try to analysis the eye-tracking data generated from the `slideshow_example.psyexp`  procedure. I try to connect eye-tracking.tsv and msg.tsv, but there is something wrong with `system_time_stamp`.

Thanks so much!

**Comment by marcus-nystrom** [comment]
> Hi, Marcus, do you have additional Python (or R) scripts for analysis and visualization of .tsv eye-tracking data. I have try to analysis the eye-tracking data generated from the `slideshow_example.psyexp` procedure. I try to connect eye-tracking.tsv and msg.tsv, but there is something wrong with `system_time_stamp`.
> 
> Thanks so much!

Hi YuanboBQ, 

I just added Python code (see resources) extract trial data and detect fixations using the I2MC-algorithm
